spring:
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT:3306}/${SPRING_DATASOURCE_DATABASE}?createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
axon:
  kafka:
    fetcher:
      enabled: false
    publisher:
      enabled: false
app:
  disable-kafka: true