spring:
  profiles:
    active: inmem
    group:
      inmem:
        - common
        - app-inmem
      axon:
        - common
        - app-axonserver
      kafka-single:
        - common
        - app-kafka-single-cluster
      kafka-single-sasl:
        - common
        - app-kafka-single-sasl
      prod:
        - common
        - app-kafka-multiple-cluster
