spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
axon:
  axonserver:
    enabled: false
  kafka:
    client-id: warehouse-command-service
    producer:
      retries: 0
    consumer:
      event-processor-mode: tracking
    properties:
      sasl.mechanism: PLAIN
      security.protocol: SASL_PLAINTEXT
    default-topic: axon-warehouse-topic
    bootstrap-servers: localhost:9092
application:
  kafka:
    topics: axon-order-topic,axon-payment-topic,axon-warehouse-topic