spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
axon:
  axonserver:
    enabled: false
  kafka:
    client-id: order-command-service
    producer:
      retries: 0
    consumer:
      event-processor-mode: tracking
    properties:
      security.protocol: PLAINTEXT
    default-topic: axon-order-topic
    bootstrap-servers: ec2-35-77-200-13.ap-northeast-1.compute.amazonaws.com:29092
application:
  kafka:
    topics: axon-order-topic,axon-payment-topic,axon-warehouse-topic
#    publisher:
#      confirmation-mode: transactional

#spring:
#  datasource:
#    url: jdbc:mysql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT:3306}/${SPRING_DATASOURCE_DATABASE}?createDatabaseIfNotExist=true
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database: mysql
#axon:
#  kafka:
#    client-id: order-command-service
#    producer:
#      retries: 0
#      bootstrap-servers: localhost:29092
#    consumer:
#      bootstrap-servers: localhost:29092,localhost:29192,localhost:29292
#      event-processor-mode: tracking
#    properties:
#      security.protocol: PLAINTEXT
#    default-topic: axon-order-topic
#    bootstrap-servers: localhost:9092,localhost:9192,localhost:9292
##    publisher:
##      confirmation-mode: transactional